@startuml LAYOUT_WITH_LEGEND Sample
'!define NetInclude
!includeurl .\C4-PlantUML\C4_Container.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

Person(admin, "App Testers")
System(PyModSim, "PyModSim")


Rel(admin,PyModSim,"User","Computer")


@enduml