@startuml SimSwissKnife
'!define NetInclude
!includeurl .\C4-PlantUML\C4_Context.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

Person(admin, "SCADA Testers")


System(SimSwissKnife, "SimSwissKnife Application")
SystemDb_Ext(DataBase,"DataBase","MSSQL")


System_Ext(SCADA_Porject, "SCADA Project")
Rel_R(SCADA_Porject,SimSwissKnife,"ModbusRTU/ModbusTCP","RS485/Network")
Rel(admin,SimSwissKnife,"User","Computer")
Rel(admin,SCADA_Porject,"User","Computer")
Rel_D(SCADA_Porject,DataBase,"ODBC","Network")
Rel(SimSwissKnife,DataBase,"PySQL","Network")
@enduml