@startuml SimSwissKnife Container
'!define NetInclude
!includeurl .\C4-PlantUML\C4_Container.puml
LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

Person(admin, "SCADA Testers")
System_Ext(SCADA_Porject, "SCADA Project")
System_Boundary(C1, "SimSwissKnife Application"){
    Container(PyModSim, "PyModSim", "Python")
    Container(PyDataBaseSim, "PyDataBaseSim", "Python")
    
}
SystemDb_Ext(DataBase,"DataBase","MSSQL")

Rel(admin,SCADA_Porject,"User","Computer")


Rel(SCADA_Porject,PyModSim,"ModbusRTU or ModbusTCP","rs485 or network")
Rel_D(SCADA_Porject,DataBase,"ODBC","Network")
Rel_L(PyDataBaseSim,DataBase,"PySQL","Network")
Rel(admin,PyDataBaseSim,"User","Computer")
Rel(admin,PyModSim,"User","Computer")
Lay_D(PyModSim,PyDataBaseSim)
@enduml